/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import logica.Mundo;

/**
 *
 * @author thebar70
 */
public class Almacenar extends javax.swing.JFrame {

    /**
     * Creates new form jFrameBodeja
     */
    private Mundo world=new Mundo();
    public Almacenar() {
        initComponents();
        visibilidadComponentes(false);
        iniciar_componentesTitulo();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBoxEmpaque = new javax.swing.JComboBox<>();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelEmpaque = new javax.swing.JLabel();
        jLabelDetallable = new javax.swing.JLabel();
        jComboBoxBetallable = new javax.swing.JComboBox<>();
        jLabelPrecio = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jLabelUnidades = new javax.swing.JLabel();
        jTextFieldUnidades = new javax.swing.JTextField();
        jLabelPrecioUnidad = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jTextFieldPrecioUnidad = new javax.swing.JTextField();
        jLabelEstado = new javax.swing.JLabel();
        jLabelFondoTitulo = new javax.swing.JLabel();
        jLabelCuerpo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Agregar Nuevo Producto a Bodega");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabelStock.setText("Stock");
        getContentPane().add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 110, -1));

        jComboBoxEmpaque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paquete", "Unidad" }));
        jComboBoxEmpaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmpaqueActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxEmpaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jTextFieldStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStockActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 80, -1));

        jLabelEmpaque.setText("Empaque");
        getContentPane().add(jLabelEmpaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabelDetallable.setText("Detallable");
        getContentPane().add(jLabelDetallable, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, -1));

        jComboBoxBetallable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));
        jComboBoxBetallable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBetallableActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxBetallable, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        jLabelPrecio.setText("Precio");
        getContentPane().add(jLabelPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));
        getContentPane().add(jTextFieldPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 80, -1));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, -1, -1));

        jLabelUnidades.setText("UnidadesXPaquete");
        getContentPane().add(jLabelUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        getContentPane().add(jTextFieldUnidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 110, -1));

        jLabelPrecioUnidad.setText("PrecioXUnidad");
        getContentPane().add(jLabelPrecioUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelUsuario.setText("Usuario: Administrador");
        getContentPane().add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabelFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelFecha.setText("----");
        getContentPane().add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 30));
        getContentPane().add(jTextFieldPrecioUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 100, -1));

        jLabelEstado.setText("---");
        getContentPane().add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabelFondoTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/titulos.jpg"))); // NOI18N
        getContentPane().add(jLabelFondoTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 60));

        jLabelCuerpo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cuerpo.jpg"))); // NOI18N
        getContentPane().add(jLabelCuerpo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 820, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void visibilidadComponentes( boolean visible){
        this.jLabelUnidades.setVisible(visible);
        this.jLabelPrecioUnidad.setVisible(visible);
        this.jTextFieldPrecioUnidad.setVisible(visible);
        this.jTextFieldUnidades.setVisible(visible);
    }
    private void iniciar_componentesTitulo(){
        SimpleDateFormat formateador = new SimpleDateFormat("dd-MM-yyyy");
        this.jLabelFecha.setText("FECHA: "+formateador.format(world.getFechaActual()));
        
            System.out.println("eele.--"+ world.elementos_bodega());
        
        
    }
    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStockActionPerformed

    private void jComboBoxEmpaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmpaqueActionPerformed
        // TODO add your handling code here:
        int selecccion=this.jComboBoxEmpaque.getSelectedIndex();
        if(selecccion==1){
            this.jComboBoxBetallable.setEnabled(false);
            visibilidadComponentes(false);
            this.jComboBoxBetallable.setSelectedIndex(0);
        }
        if(selecccion==0){
            this.jComboBoxBetallable.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBoxEmpaqueActionPerformed

    private void jComboBoxBetallableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBetallableActionPerformed
        // TODO add your handling code here:
        int seleccion=this.jComboBoxBetallable.getSelectedIndex();
        if(seleccion==1){
            visibilidadComponentes(true);
        }
        else
            visibilidadComponentes(false);
    }//GEN-LAST:event_jComboBoxBetallableActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // TODO add your handling code here:
        String nombre=this.jTextFieldNombre.getText();
        int stock=Integer.parseInt(this.jTextFieldStock.getText());
        float precio=Float.parseFloat(this.jTextFieldPrecio.getText());
        String empaque=this.jComboBoxEmpaque.getSelectedItem().toString();
        int det=this.jComboBoxBetallable.getSelectedIndex();
        float precioUnidad=Float.parseFloat(this.jTextFieldPrecioUnidad.getText());
        int unidades=Integer.parseInt(this.jTextFieldUnidades.getText());
        boolean detallable=false;
        
        if(det==1)
            detallable=true;
        try {
            world.crear_nuevo_producto(nombre, stock, empaque, detallable, precioUnidad, unidades, precio);
        } catch (SQLException ex) {
            Logger.getLogger(Almacenar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacenar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacenar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JComboBox<String> jComboBoxBetallable;
    private javax.swing.JComboBox<String> jComboBoxEmpaque;
    private javax.swing.JLabel jLabelCuerpo;
    private javax.swing.JLabel jLabelDetallable;
    private javax.swing.JLabel jLabelEmpaque;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelFondoTitulo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JLabel jLabelPrecioUnidad;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelUnidades;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldPrecioUnidad;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldUnidades;
    // End of variables declaration//GEN-END:variables
}
